# Options from https://github.com/michaelherold/codeclimate-sass-lint/tree/master/config/contents
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'table'
  formatter: 'table'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 0
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 2
  no-debug: 2
  no-ids: 0
  no-invalid-hex: 1
  no-important: 2
  url-quotes: 2
  one-declaration-per-line: 2
  quotes:
    - 1
    -
      stlye: single
  no-color-keywords: 2
  hex-length:
    - 1
    -
      style: long
  hex-notation:
    - 2
    -
      style: uppercase
  indentation:
    - 1
    -
      character: space
      size: 4
  property-sort-order:
    - 2
    -
      order: concentric
      ignore-custom-properties: true
